[package]
name = "stack-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.2"
reqwest = { version = "0.11.15", features = ["blocking"] }
select = "0.6.0"
